# Use an official base image as a starting point
FROM ubuntu:22.04

# Update the package list and install Ansible and other dependencies
RUN apt-get update -y && \
    apt-get install -y software-properties-common jq

RUN add-apt-repository -y --update ppa:ansible/ansible

RUN apt-get install -y ansible

# Set the default working directory for Ansible playbooks
WORKDIR /ansible

# Define an entry point if needed
# ENTRYPOINT ["ansible-playbook"]